# 在官方的镜像上增加简单
FROM php:7.3.2-fpm
# 安装扩展
RUN apt-get update \
&& apt-get install -y libfreetype6-dev libmcrypt-dev libjpeg-dev libpng-dev \
&& docker-php-ext-configure gd --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2 --with-png-dir=/usr/include --with-jpeg-dir=/usr/include \
&& docker-php-ext-install gd \
&& docker-php-ext-install mcrypt mysqli mysql pdo_mysql zip
# 安装扩展
RUN pecl install redis \
&& echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini \
&& pecl install channel://pecl.php.net/msgpack-0.5.7 \
&& echo "extension=msgpack.so" > /usr/local/etc/php/conf.d/msgpack.ini \
&& pecl install mongodb \
&& echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/mongodb.ini \
&& pecl install mongo \
&& echo "extension=mongo.so" > /usr/local/etc/php/conf.d/mongo.ini \
&& pecl clear-cache
# 安装composer
RUN cd / \
&& php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php \
&& php composer-setup.php  --filename=composer  --install-dir=/usr/local/bin/ \
&& rm composer-setup.php \
&& composer global require "laravel/lumen-installer" \
&& composer global require "laravel/installer" \
&& composer clearcache \
&& composer clear-cache
# 解决时区问题
ENV TZ "Asia/Shanghai"
# 终端设置
ENV TERM xterm